// Multi-competition simulator layer: competition -> edition/year -> team pool -> format
const WC26=['Canada','Mexico','United States','Australia','Iraq','Iran','Japan','Jordan','South Korea','Qatar','Saudi Arabia','Uzbekistan','Algeria','Cabo Verde','DR Congo','Côte d’Ivoire','Egypt','Ghana','Morocco','Senegal','South Africa','Tunisia','Curaçao','Haiti','Panama','Argentina','Brazil','Colombia','Ecuador','Paraguay','Uruguay','New Zealand','Austria','Belgium','Bosnia and Herzegovina','Croatia','Czechia','England','France','Germany','Netherlands','Norway','Portugal','Scotland','Spain','Sweden','Switzerland','Türkiye'];
const EURO28=['Albania','Austria','Belgium','Croatia','Czechia','Denmark','England','France','Georgia','Germany','Hungary','Italy','Netherlands','Poland','Portugal','Romania','Scotland','Serbia','Slovakia','Slovenia','Spain','Switzerland','Türkiye','Ukraine'];
const COPA28=['Argentina','Bolivia','Brazil','Canada','Chile','Colombia','Costa Rica','Ecuador','Jamaica','Mexico','Panama','Paraguay','Peru','United States','Uruguay','Venezuela'];
const COMPETITION_CONFIG={
 worldcup:{name:'World Cup',editions:{2026:{teams:WC26,groupCount:12,groupSize:4,thirds:8,firstKnockout:32,note:''},2030:{teams:WC26,groupCount:12,groupSize:4,thirds:8,firstKnockout:32,note:'2030 is projected for now. Spain, Portugal, Morocco, Argentina, Paraguay and Uruguay are treated as confirmed hosts/centenary participants; the remaining field is provisional.'}}},
 euro:{name:'European Championship (EURO)',editions:{2028:{teams:EURO28,groupCount:6,groupSize:4,thirds:4,firstKnockout:16,note:'2028 team field is projected until qualifying determines the actual finalists.'}}},
 copa:{name:'Copa América',editions:{2028:{teams:COPA28,groupCount:4,groupSize:4,thirds:0,firstKnockout:8,note:'2028 team field is projected until the actual tournament field is determined.'}}}
};
const COMP_ELO=window.__competitionElo||{};
function compElo(t){return Number(COMP_ELO[t]??window.__tournamentTeams?.[t]??1500)}
function compProfile(t){return{elo:compElo(t)}}
function compPoisson(l){l=Math.max(.01,Number(l)||.01);const L=Math.exp(-l);let k=0,p=1;do{k++;p*=Math.random()}while(p>L);return k-1}
function compMatch(a,b){const p=window.SoccerModel.predictMatch(compProfile(a),compProfile(b),'neutral');const ga=compPoisson(p.expectedGoals.team1),gb=compPoisson(p.expectedGoals.team2);const m={a,b,regulationGa:ga,regulationGb:gb,ga,gb,extra:false,penalties:false};if(ga===gb){m.extra=true;m.ga+=compPoisson(p.expectedGoals.team1/3);m.gb+=compPoisson(p.expectedGoals.team2/3);m.extraGa=m.ga;m.extraGb=m.gb;if(m.ga===m.gb){let ak=0,bk=0;for(let i=0;i<5;i++){if(Math.random()<.75)ak++;if(Math.random()<.75)bk++}while(ak===bk){if(Math.random()<.75)ak++;if(Math.random()<.75)bk++}m.penalties=true;m.penaltyScore=`${ak}–${bk}`;m.winner=ak>bk?a:b}else m.winner=m.ga>m.gb?a:b}else m.winner=ga>gb?a:b;return m}
function compGroups(c){const ranked=c.teams.slice().sort((a,b)=>compElo(b)-compElo(a));const potSize=c.teams.length/4;const pots=[ranked.slice(0,potSize),ranked.slice(potSize,potSize*2),ranked.slice(potSize*2,potSize*3),ranked.slice(potSize*3)];pots.forEach(p=>{for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}});const groups=Array.from({length:c.groupCount},()=>[]);pots.forEach(p=>p.forEach((t,i)=>groups[i].push(t)));return groups}
function compStandings(group,matches){const r=Object.fromEntries(group.map(t=>[t,{team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0}]));matches.forEach(m=>{const a=r[m.a],b=r[m.b];a.gf+=m.regulationGa;a.ga+=m.regulationGb;b.gf+=m.regulationGb;b.ga+=m.regulationGa;a.gd=a.gf-a.ga;b.gd=b.gf-b.ga;if(m.regulationGa>m.regulationGb){a.p+=3;a.w++;b.l++}else if(m.regulationGb>m.regulationGa){b.p+=3;b.w++;a.l++}else{a.p++;b.p++;a.d++;b.d++}});return Object.values(r).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||compElo(b.team)-compElo(a.team))}
function simulateCompetition(c){const groups=compGroups(c),tables=[],matchesByGroup=[];groups.forEach(g=>{const ms=[];for(let i=0;i<g.length;i++)for(let j=i+1;j<g.length;j++)ms.push(compMatch(g[i],g[j]));matchesByGroup.push(ms);tables.push(compStandings(g,ms))});let q=[];tables.forEach(t=>q.push(t[0].team,t[1].team));if(c.thirds)q.push(...tables.map(t=>t[2]).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||compElo(b.team)-compElo(a.team)).slice(0,c.thirds).map(x=>x.team));const stage={round32:[],round16:[],quarterfinals:[],semifinals:[],final:[],champion:null};if(c.firstKnockout===32)stage.round32=q.slice();if(c.firstKnockout===16)stage.round16=q.slice();if(c.firstKnockout===8)stage.quarterfinals=q.slice();let k=q.slice();while(k.length>1){const w=[];for(let i=0;i<k.length;i+=2)w.push(compMatch(k[i],k[i+1]).winner);k=w;if(k.length===16)stage.round16=k.slice();else if(k.length===8)stage.quarterfinals=k.slice();else if(k.length===4)stage.semifinals=k.slice();else if(k.length===2)stage.final=k.slice()}stage.champion=k[0]||null;return{groups,tables,matchesByGroup,stage}}
function compEscape(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function compStages(c){return c.firstKnockout===32?[['round32','Round of 32'],['round16','Round of 16'],['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]:c.firstKnockout===16?[['round16','Round of 16'],['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]:[['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]}
function currentCompetition(id,yearId){const key=document.querySelector(id)?.value||'worldcup';const cfg=COMPETITION_CONFIG[key];const years=Object.keys(cfg.editions);const year=document.querySelector(yearId)?.value||years[0];return{key,year,cfg,...cfg.editions[year]}}
function setYearOptions(selectId,competitionKey,preferredYear){const select=document.querySelector(selectId);if(!select)return;const years=Object.keys(COMPETITION_CONFIG[competitionKey].editions);const old=preferredYear&&years.includes(String(preferredYear))?String(preferredYear):years[0];select.innerHTML=years.map(y=>`<option value="${y}">${y}${competitionKey==='worldcup'&&y==='2030'?' — projected':''}</option>`).join('');select.value=old}
function updateCompetitionYearUI(typeId,yearId,labelId,noteId){const key=document.querySelector(typeId)?.value||'worldcup';setYearOptions(yearId,key);const cfg=COMPETITION_CONFIG[key];const label=document.querySelector(labelId);if(label)label.textContent=cfg.name==='World Cup'?'World Cup edition':cfg.name+' edition';const c=currentCompetition(typeId,yearId);const note=document.querySelector(noteId);if(note){note.textContent=c.note;note.hidden=!c.note}}
function compStatsHTML(c,stats,count){const rows=Object.values(stats).sort((a,b)=>b.champion-a.champion||b.final-a.final||b.semifinals-a.semifinals||b.quarterfinals-a.quarterfinals||b.round16-a.round16||b.round32-a.round32);let h=`<section class="card"><h2>${compEscape(c.name)} ${c.year} — ${count.toLocaleString()} simulations</h2><p class="muted">Percentage of simulations in which each team reached each stage.</p><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Team</th>${compStages(c).map(s=>`<th>${s[1]}</th>`).join('')}</tr></thead><tbody>`;rows.forEach(r=>{h+=`<tr><th>${compEscape(r.team)}</th>${compStages(c).map(s=>`<td>${((r[s[0]]/count)*100).toFixed(1)}%</td>`).join('')}</tr>`});return h+'</tbody></table></div></section>'}
function installCompetitionUI(){const statsType=document.querySelector('#competitionType'),tourType=document.querySelector('#tournamentCompetitionType');if(!statsType||!tourType)return;const statsYear=document.querySelector('#statsWorldCupYear'),tourYear=document.querySelector('#wcYear'),statsLabel=document.querySelector('#statsWorldCupYearLabel'),tourLabel=document.querySelector('#wcYearLabel'),runMany=document.querySelector('#runManySimulations'),status=document.querySelector('#statsStatus'),output=document.querySelector('#simulationStats'),runOne=document.querySelector('#runTournament'),tourStatus=document.querySelector('#tournamentStatus'),tourOutput=document.querySelector('#tournamentResults');function refreshStats(){const old=statsYear.value;updateCompetitionYearUI('#competitionType','#statsWorldCupYear','#statsWorldCupYearLabel','#stats2030Note');if(old&&[...statsYear.options].some(o=>o.value===old))statsYear.value=old;output.hidden=true;const c=currentCompetition('#competitionType','#statsWorldCupYear');status.textContent=`Ready — ${c.name} ${c.year}.`};function refreshTour(){const old=tourYear.value;updateCompetitionYearUI('#tournamentCompetitionType','#wcYear','#wcYearLabel','#wc2030Note');if(old&&[...tourYear.options].some(o=>o.value===old))tourYear.value=old;tourOutput.hidden=true;const c=currentCompetition('#tournamentCompetitionType','#wcYear');tourStatus.textContent=`Ready — ${c.name} ${c.year}.`}
function runMany(){const c=currentCompetition('#competitionType','#statsWorldCupYear'),count=Math.max(10,Math.min(10000,Math.floor(Number(document.querySelector('#simulationCount').value)||1000)));document.querySelector('#simulationCount').value=count;runMany.disabled=true;output.hidden=true;const stats=Object.fromEntries(c.teams.map(t=>[t,{team:t,round32:0,round16:0,quarterfinals:0,semifinals:0,final:0,champion:0}]));let done=0;const batch=()=>{const end=Math.min(done+10,count);for(;done<end;done++){const r=simulateCompetition(c).stage;Object.keys(stats).forEach(t=>{if(r.round32.includes(t))stats[t].round32++;if(r.round16.includes(t))stats[t].round16++;if(r.quarterfinals.includes(t))stats[t].quarterfinals++;if(r.semifinals.includes(t))stats[t].semifinals++;if(r.final.includes(t))stats[t].final++;if(r.champion===t)stats[t].champion++})}status.textContent=`${c.name} ${c.year}: ${done.toLocaleString()}/${count.toLocaleString()}…`;if(done<count)return setTimeout(batch,0);output.innerHTML=compStatsHTML(c,stats,count);output.hidden=false;status.textContent=`${c.name} ${c.year}: finished ${count.toLocaleString()} simulations.`;runMany.disabled=false};batch()}
function runOneComp(){const c=currentCompetition('#tournamentCompetitionType','#wcYear'),d=simulateCompetition(c);let h=`<div class="wc-summary card"><h2>${compEscape(c.name)} ${c.year} simulation complete</h2><p>${c.groupCount} groups of ${c.groupSize} were drawn automatically from four Elo pots.</p>${c.note?`<p class="muted">${compEscape(c.note)}</p>`:''}<p><strong>Champion:</strong> ${compEscape(d.stage.champion||'—')}</p></div>`;d.groups.forEach((g,i)=>{h+=`<section class="card wc-group wc-stage" data-stage="group-${i}"><h3>Group ${String.fromCharCode(65+i)}</h3><table class="wc-table"><thead><tr><th>Team</th><th>Pts</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th></tr></thead><tbody>`;d.tables[i].forEach(r=>h+=`<tr><th>${compEscape(r.team)}</th><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd}</td></tr>`);h+='</tbody></table><h4>Matches</h4><div class="match-list">';d.matchesByGroup[i].forEach(m=>h+=`<div class="match-row"><span>${compEscape(m.a)}</span><strong>${m.regulationGa}–${m.regulationGb}</strong><span>${compEscape(m.b)}</span></div>`);h+='</div></section>'});let k=d.stage.round32.length?d.stage.round32.slice():d.stage.round16.length?d.stage.round16.slice():d.stage.quarterfinals.slice();let roundTitle=d.stage.round32.length?'Round of 32':d.stage.round16.length?'Round of 16':'Quarter-finals';while(k.length>1){const pairs=[];for(let i=0;i<k.length;i+=2)pairs.push(compMatch(k[i],k[i+1]));h+=`<section class="card wc-stage"><h3>${roundTitle}</h3><div class="knockout-list">`;pairs.forEach(m=>{let s=`${m.regulationGa}–${m.regulationGb}`;if(m.extra)s+=` <small>(ET: ${m.extraGa}–${m.extraGb})</small>`;if(m.penalties)s+=` <small>(P: ${m.penaltyScore})</small>`;h+=`<div class="match-row"><span>${compEscape(m.a)}</span><strong>${s}</strong><span>${compEscape(m.b)}</span></div>`});h+='</div></section>';k=pairs.map(m=>m.winner);roundTitle=k.length===16?'Round of 16':k.length===8?'Quarter-finals':k.length===4?'Semi-finals':'Final'}tourOutput.innerHTML=h;tourOutput.hidden=false;tourStatus.textContent=`${c.name} ${c.year}: 1 simulation complete.`}
runMany.onclick=runMany;runOne.onclick=runOneComp;statsType.onchange=refreshStats;statsYear.onchange=()=>{const c=currentCompetition('#competitionType','#statsWorldCupYear');status.textContent=`Ready — ${c.name} ${c.year}.`;output.hidden=true};tourType.onchange=refreshTour;tourYear.onchange=()=>{const c=currentCompetition('#tournamentCompetitionType','#wcYear');tourStatus.textContent=`Ready — ${c.name} ${c.year}.`;tourOutput.hidden=true};refreshStats();refreshTour()}
window.addEventListener('DOMContentLoaded',()=>setTimeout(installCompetitionUI,0));setTimeout(installCompetitionUI,50);