const fallbackTeams={"Brazil":1880,"France":1860,"Spain":1845,"Argentina":1835,"England":1810,"Portugal":1795,"Germany":1785,"Netherlands":1765,"Italy":1745,"Belgium":1735};
let teams=fallbackTeams;let teamStats={};let language='en';
const home=document.querySelector('#home'),away=document.querySelector('#away'),venue=document.querySelector('#venue'),homeElo=document.querySelector('#homeElo'),awayElo=document.querySelector('#awayElo'),homeOut=document.querySelector('#homeOut'),awayOut=document.querySelector('#awayOut');
const countryNames={ES:'Spain',AR:'Argentina',EN:'England',FR:'France',CO:'Colombia',PT:'Portugal',BR:'Brazil',NL:'Netherlands',NO:'Norway',BE:'Belgium',CH:'Switzerland',MX:'Mexico',DE:'Germany',MA:'Morocco',JP:'Japan',HR:'Croatia',EC:'Ecuador',DK:'Denmark',IT:'Italy',TR:'Turkey',UY:'Uruguay',AT:'Austria',SN:'Senegal',PY:'Paraguay',AU:'Australia',UA:'Ukraine',RU:'Russia',NG:'Nigeria',IR:'Iran',DZ:'Algeria',US:'United States',GB:'England',SC:'Scotland',SQ:'Scotland',GR:'Greece',EG:'Egypt',RS:'Serbia',VE:'Venezuela',SE:'Sweden',CA:'Canada',CI:'Ivory Coast',KR:'South Korea',CL:'Chile',KO:'Kosovo',HU:'Hungary',PL:'Poland',CD:'DR Congo',PE:'Peru',IE:'Ireland',SI:'Slovenia',WA:'Wales',CZ:'Czech Republic',SK:'Slovakia',PA:'Panama',GE:'Georgia',IL:'Israel',RO:'Romania',UZ:'Uzbekistan',JO:'Jordan',BO:'Bolivia',CV:'Cape Verde',AL:'Albania',CM:'Cameroon',CR:'Costa Rica',BA:'Bosnia and Herzegovina',EI:'Ireland',SA:'Saudi Arabia',GH:'Ghana',HN:'Honduras',IS:'Iceland',TN:'Tunisia',IQ:'Iraq',ZA:'South Africa'};
const countryNamesZh={Spain:'西班牙',Argentina:'阿根廷',England:'英格兰',France:'法国',Colombia:'哥伦比亚',Portugal:'葡萄牙',Brazil:'巴西',Netherlands:'荷兰',Norway:'挪威',Belgium:'比利时',Switzerland:'瑞士',Mexico:'墨西哥',Germany:'德国',Morocco:'摩洛哥',Japan:'日本',Croatia:'克罗地亚',Ecuador:'厄瓜多尔',Denmark:'丹麦',Italy:'意大利',Turkey:'土耳其',Uruguay:'乌拉圭',Austria:'奥地利',Senegal:'塞内加尔',Paraguay:'巴拉圭',Australia:'澳大利亚',Ukraine:'乌克兰',Russia:'俄罗斯',Nigeria:'尼日利亚',Iran:'伊朗',Algeria:'阿尔及利亚','United States':'美国',Scotland:'苏格兰',Greece:'希腊',Egypt:'埃及',Serbia:'塞尔维亚',Venezuela:'委内瑞拉',Sweden:'瑞典',Canada:'加拿大','Ivory Coast':'科特迪瓦','South Korea':'韩国',Chile:'智利',Kosovo:'科索沃',Hungary:'匈牙利',Poland:'波兰','DR Congo':'刚果民主共和国',Peru:'秘鲁',Ireland:'爱尔兰',Slovenia:'斯洛文尼亚',Wales:'威尔士','Czech Republic':'捷克','Slovakia':'斯洛伐克',Panama:'巴拿马',Georgia:'格鲁吉亚',Israel:'以色列',Romania:'罗马尼亚',Uzbekistan:'乌兹别克斯坦',Jordan:'约旦',Bolivia:'玻利维亚','Cape Verde':'佛得角',Albania:'阿尔巴尼亚',Cameroon:'喀麦隆','Costa Rica':'哥斯达黎加','Bosnia and Herzegovina':'波斯尼亚和黑塞哥维那','Saudi Arabia':'沙特阿拉伯',Ghana:'加纳',Honduras:'洪都拉斯',Iceland:'冰岛',Tunisia:'突尼斯',Iraq:'伊拉克','South Africa':'南非'};
function displayName(item){const raw=String(item.team??item.code??item.name??'').trim();return countryNames[raw.toUpperCase()]||raw;}
function shownName(name){return language==='zh'?(countryNamesZh[name]||name):name;}
function getStats(name,elo){return{elo,...(teamStats[name]||{})};}
function populateTeams(){home.replaceChildren();away.replaceChildren();Object.keys(teams).forEach(name=>{home.add(new Option(shownName(name),name));away.add(new Option(shownName(name),name));});const names=Object.keys(teams);home.value=teams.Brazil?'Brazil':names[0];away.value=teams.France?'France':names[1]||names[0];syncRatings();}
function updateLabels(){homeOut.value=homeElo.value;awayOut.value=awayElo.value;}
function syncRatings(){homeElo.value=teams[home.value]??1500;awayElo.value=teams[away.value]??1500;updateLabels();analyze();}
const text={en:{title:'Match Lab',subtitle:'Explore team strength, expected results, and goal projections.',comparison:'Team comparison',team1:'Team 1',team2:'Team 2',venue:'Venue',neutral:'Neutral',home:'Team 1 home',away:'Team 2 home',analyze:'Analyze match',win:'Team 1 win',draw:'Draw',loss:'Team 2 win',xg1:'Team 1 expected goals',xg2:'Team 2 expected goals',likely:'Most likely score',scoreline:'Most likely scoreline',explain:'The scoreline above shows the predicted goals for each team.',how:'How the model works',howText:'The model combines Elo with attacking and defensive indicators, chance creation, shots, possession, and recent form. It converts the resulting expected goals into scoreline and win/draw/loss probabilities.',disclaimer:'This is an educational model. Its weights should be backtested against historical matches before treating it as a calibrated forecasting system.',toggle:'中文'},zh:{title:'比赛分析实验室',subtitle:'探索球队实力、比赛预测和进球预测。',comparison:'球队对比',team1:'球队 1',team2:'球队 2',venue:'比赛场地',neutral:'中立场地',home:'球队 1 主场',away:'球队 2 主场',analyze:'分析比赛',win:'球队 1 获胜',draw:'平局',loss:'球队 2 获胜',xg1:'球队 1 预期进球',xg2:'球队 2 预期进球',likely:'最可能比分',scoreline:'最可能的比分',explain:'上面的比分显示了每支球队预测的进球数。',how:'模型原理',howText:'模型结合了Elo评分、进攻和防守指标、创造机会、射门、控球率以及近期状态，并将预期进球转换为比分和胜/平/负概率。',disclaimer:'这是一个教育用途的模型。在将其视为经过校准的预测系统之前，应使用历史比赛进行回测。',toggle:'English'}};
function setLanguage(){const t=text[language];document.documentElement.lang=language==='zh'?'zh-CN':'en';const ids={title:'title',subtitle:'subtitle',comparison:'comparisonTitle',team1:'team1Label',team2:'team2Label',venue:'venueLabel',analyze:'analyze',win:'team1WinLabel',draw:'drawLabel',loss:'team2WinLabel',xg1:'team1XgLabel',xg2:'team2XgLabel',likely:'likelyScoreLabel',scoreline:'scorelineTitle',explain:'scoreExplanation',how:'howTitle',howText:'howText',disclaimer:'disclaimer',toggle:'languageToggle'};for(const [key,id] of Object.entries(ids)){const el=document.querySelector('#'+id);if(el)el.textContent=t[key];}venue.options[0].textContent=t.neutral;venue.options[1].textContent=t.home;venue.options[2].textContent=t.away;populateTeams();document.querySelector('#scoreHomeName').textContent=shownName(home.value);document.querySelector('#scoreAwayName').textContent=shownName(away.value);analyze();}
function analyze(){if(!window.SoccerModel){console.error('SoccerModel has not loaded.');return;}const team1=getStats(home.value,Number(homeElo.value)),team2=getStats(away.value,Number(awayElo.value));const result=window.SoccerModel.analyzeMatch(team1,team2,venue.value),p=result.probabilities,goals=result.prediction.expectedGoals,best=result.mostLikelyScores?.[0];document.querySelector('#win').textContent=`${(p.team1Win*100).toFixed(1)}%`;document.querySelector('#draw').textContent=`${(p.draw*100).toFixed(1)}%`;document.querySelector('#loss').textContent=`${(p.team2Win*100).toFixed(1)}%`;document.querySelector('#xgHome').textContent=goals.team1.toFixed(2);document.querySelector('#xgAway').textContent=goals.team2.toFixed(2);const n1=shownName(home.value),n2=shownName(away.value);document.querySelector('#likelyScore').textContent=best?`${n1} ${best.team1Goals}–${best.team2Goals} ${n2}`:'—';document.querySelector('#scoreHomeName').textContent=n1;document.querySelector('#scoreAwayName').textContent=n2;document.querySelector('#scoreHomeGoals').textContent=best?.team1Goals??'—';document.querySelector('#scoreAwayGoals').textContent=best?.team2Goals??'—';if(best)document.querySelector('#scoreExplanation').textContent=language==='zh'?`模型最可能的准确比分是 ${n1} ${best.team1Goals}–${best.team2Goals} ${n2}。`: `The model's most likely exact score is ${n1} ${best.team1Goals}–${best.team2Goals} ${n2}.`;document.querySelector('#barHome').style.width=`${p.team1Win*100}%`;document.querySelector('#barDraw').style.width=`${p.draw*100}%`;document.querySelector('#barAway').style.width=`${p.team2Win*100}%`;}
async function loadRatings(){try{const response=await fetch(`ratings.json?cacheBust=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.teams)||!data.teams.length)throw new Error('No ratings');teams=Object.fromEntries(data.teams.map(item=>[displayName(item),Number(item.elo)]));populateTeams();const status=document.querySelector('#dataStatus');if(status)status.textContent=language==='zh'?`已加载实时评分 · ${data.teams.length} 支球队`:`Live ratings loaded · ${data.teams.length} teams`;}catch(error){populateTeams();const status=document.querySelector('#dataStatus');if(status)status.textContent=language==='zh'?'正在使用内置备用评分':'Using built-in fallback ratings · automatic update has not run yet';console.warn('Could not load ratings.json:',error);}}
async function loadTeamStats(){try{const response=await fetch(`team-stats.json?cacheBust=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);teamStats=await response.json();analyze();}catch(error){console.info('No team-stats.json yet. Using default statistics.');}}
document.querySelector('#languageToggle').addEventListener('click',()=>{language=language==='en'?'zh':'en';setLanguage();});home.addEventListener('change',syncRatings);away.addEventListener('change',syncRatings);venue.addEventListener('change',analyze);homeElo.addEventListener('input',()=>{updateLabels();analyze();});awayElo.addEventListener('input',()=>{updateLabels();analyze();});document.querySelector('#analyze').addEventListener('click',analyze);populateTeams();loadRatings();loadTeamStats();
