const $=s=>document.querySelector(s);let teams={},stats={},lang='en';
const home=$('#home'),away=$('#away'),venue=$('#venue'),homeElo=$('#homeElo'),awayElo=$('#awayElo');
const fallback={Brazil:1880,France:1860,Spain:1845,Argentina:1835,England:1810,Portugal:1795,Germany:1785,Netherlands:1765,Italy:1745,Belgium:1735,China:1424};
const codeNames={ES:'Spain',AR:'Argentina',EN:'England',FR:'France',CO:'Colombia',PT:'Portugal',BR:'Brazil',NL:'Netherlands',NO:'Norway',BE:'Belgium',CH:'Switzerland',MX:'Mexico',DE:'Germany',MA:'Morocco',JP:'Japan',HR:'Croatia',EC:'Ecuador',DK:'Denmark',IT:'Italy',TR:'Türkiye',UY:'Uruguay',AT:'Austria',SN:'Senegal',PY:'Paraguay',AU:'Australia',UA:'Ukraine',RU:'Russian Federation',NG:'Nigeria',IR:'Iran',DZ:'Algeria',US:'United States',GB:'England',SC:'Scotland',GR:'Greece',EG:'Egypt',RS:'Serbia',VE:'Venezuela',SE:'Sweden',CA:'Canada',KR:'South Korea',CL:'Chile',XK:'Kosovo',HU:'Hungary',PL:'Poland',PE:'Peru',IE:'Ireland',SI:'Slovenia',WA:'Wales',CZ:'Czechia',SK:'Slovakia',PA:'Panama',GE:'Georgia',IL:'Israel',RO:'Romania',UZ:'Uzbekistan',JO:'Jordan',BO:'Bolivia',CV:'Cabo Verde',AL:'Albania',CM:'Cameroon',CR:'Costa Rica',BA:'Bosnia and Herzegovina',SA:'Saudi Arabia',MK:'North Macedonia',ML:'Mali',GH:'Ghana',HN:'Honduras',IS:'Iceland',TN:'Tunisia',IQ:'Iraq',ZA:'South Africa',AO:'Angola',AE:'United Arab Emirates',FI:'Finland',NZ:'New Zealand',BF:'Burkina Faso',JM:'Jamaica',BY:'Belarus',HT:'Haiti',GT:'Guatemala',OM:'Oman',SY:'Syria',PS:'Palestine',GN:'Guinea',ME:'Montenegro',BG:'Bulgaria',LU:'Luxembourg',CW:'Curaçao',SR:'Suriname',KZ:'Kazakhstan',CN:'China'};
const zh={Spain:'西班牙',Argentina:'阿根廷',England:'英格兰',France:'法国',Colombia:'哥伦比亚',Portugal:'葡萄牙',Brazil:'巴西',Netherlands:'荷兰',Norway:'挪威',Belgium:'比利时',Switzerland:'瑞士',Mexico:'墨西哥',Germany:'德国',Morocco:'摩洛哥',Japan:'日本',Croatia:'克罗地亚',Ecuador:'厄瓜多尔',Denmark:'丹麦',Italy:'意大利',Türkiye:'土耳其',Uruguay:'乌拉圭',Austria:'奥地利',Senegal:'塞内加尔',Paraguay:'巴拉圭',Australia:'澳大利亚',Ukraine:'乌克兰','Russian Federation':'俄罗斯',Nigeria:'尼日利亚',Iran:'伊朗',Algeria:'阿尔及利亚','United States':'美国',Scotland:'苏格兰',Greece:'希腊',Egypt:'埃及',Serbia:'塞尔维亚',Venezuela:'委内瑞拉',Sweden:'瑞典',Canada:'加拿大','South Korea':'韩国',Chile:'智利',Kosovo:'科索沃',Hungary:'匈牙利',Poland:'波兰',Peru:'秘鲁',Ireland:'爱尔兰',Slovenia:'斯洛文尼亚',Wales:'威尔士',Czechia:'捷克',Slovakia:'斯洛伐克',Panama:'巴拿马',Georgia:'格鲁吉亚',Israel:'以色列',Romania:'罗马尼亚',Uzbekistan:'乌兹别克斯坦',Jordan:'约旦',Bolivia:'玻利维亚','Cabo Verde':'佛得角',Albania:'阿尔巴尼亚',Cameroon:'喀麦隆','Costa Rica':'哥斯达黎加','Bosnia and Herzegovina':'波斯尼亚和黑塞哥维那','Saudi Arabia':'沙特阿拉伯','North Macedonia':'北马其顿',Mali:'马里',Ghana:'加纳',Honduras:'洪都拉斯',Iceland:'冰岛',Tunisia:'突尼斯',Iraq:'伊拉克','South Africa':'南非',Angola:'安哥拉','United Arab Emirates':'阿联酋',Finland:'芬兰','New Zealand':'新西兰','Burkina Faso':'布基纳法',Jamaica:'牙买加',Belarus:'白俄罗斯',Haiti:'海地',Guatemala:'危地马拉',Oman:'阿曼',Syria:'叙利亚',Palestine:'巴勒斯坦',Guinea:'几内亚',Montenegro:'黑山',Bulgaria:'保加利亚',Luxembourg:'卢森堡',Curaçao:'库拉索',Suriname:'苏里南',Kazakhstan:'哈萨克斯坦',China:'中国'};
function normalize(n){const raw=String(n||'').trim();return codeNames[raw.toUpperCase()]||raw}
function name(n){return lang==='zh'?(zh[n]||n):n}
function rebuild(){const list=Object.entries(teams).sort((a,b)=>b[1]-a[1]);for(const s of [home,away])s.replaceChildren(...list.map(([n])=>new Option(name(n),n)));home.value=teams.Brazil?'Brazil':list[0]?.[0]||'';away.value=teams.France?'France':list[1]?.[0]||'';updateDisabled();sync()}
function updateDisabled(){for(const o of home.options)o.disabled=o.value===away.value;for(const o of away.options)o.disabled=o.value===home.value;if(home.options[home.selectedIndex]?.disabled){const o=[...home.options].find(x=>!x.disabled);if(o)home.value=o.value}if(away.options[away.selectedIndex]?.disabled){const o=[...away.options].find(x=>!x.disabled);if(o)away.value=o.value}}
function sync(){updateDisabled();homeElo.value=teams[home.value]??1500;awayElo.value=teams[away.value]??1500;analyze()}
function analyze(){if(!window.SoccerModel)return;const noDraw=$('#competitionMode')?.value==='noDraw';const r=window.SoccerModel.analyzeMatch({elo:+homeElo.value,...(stats[home.value]||{})},{elo:+awayElo.value,...(stats[away.value]||{})},venue.value,noDraw);const p=r.probabilities,g=r.prediction.expectedGoals,b=r.mostLikelyScores[0],n1=name(home.value),n2=name(away.value);$('#win').textContent=(p.team1Win*100).toFixed(1)+'%';$('#draw').textContent=(p.draw*100).toFixed(1)+'%';$('#loss').textContent=(p.team2Win*100).toFixed(1)+'%';$('#xgHome').textContent=g.team1.toFixed(2);$('#xgAway').textContent=g.team2.toFixed(2);$('#likelyScore').textContent=`${n1} ${b.team1Goals}–${b.team2Goals} ${n2}`;$('#scoreHomeName').textContent=n1;$('#scoreAwayName').textContent=n2;$('#scoreHomeGoals').textContent=b.team1Goals;$('#scoreAwayGoals').textContent=b.team2Goals;$('#barHome').style.width=p.team1Win*100+'%';$('#barDraw').style.width=p.draw*100+'%';$('#barAway').style.width=p.team2Win*100+'%'}
function setText(){const z=lang==='zh';document.documentElement.lang=z?'zh-CN':'en';const t=z?{title:'比赛分析实验室',subtitle:'探索球队实力、比赛预测和进球预测。',comparison:'球队对比',team1:'球队 1',team2:'球队 2',venue:'比赛场地',neutral:'中立场地',home:'球队 1 主场',away:'球队 2 主场',analyze:'分析比赛',win:'球队 1 获胜',draw:'平局',loss:'球队 2 获胜',xg1:'球队 1 预期进球',xg2:'球队 2 预期进球',likely:'最可能比分',scoreline:'最可能的比分',explain:'上面的比分显示每支球队预测的进球数。',how:'模型原理',toggle:'English',s1:'搜索球队 1',s2:'搜索球队 2',ph:'输入球队名称…'}:{title:'Match Lab',subtitle:'Explore team strength, expected results, and goal projections.',comparison:'Team comparison',team1:'Team 1',team2:'Team 2',venue:'Venue',neutral:'Neutral',home:'Team 1 home',away:'Team 2 home',analyze:'Analyze match',win:'Team 1 win',draw:'Draw',loss:'Team 2 win',xg1:'Team 1 expected goals',xg2:'Team 2 expected goals',likely:'Most likely score',scoreline:'Most likely scoreline',explain:'The scoreline above shows the predicted goals for each team.',how:'How the model works',toggle:'中文',s1:'Search Team 1',s2:'Search Team 2',ph:'Type a team name…'};const ids={title:'title',subtitle:'subtitle',comparison:'comparisonTitle',team1:'team1Label',team2:'team2Label',venue:'venueLabel',analyze:'analyze',win:'team1WinLabel',draw:'drawLabel',loss:'team2WinLabel',xg1:'team1XgLabel',xg2:'team2XgLabel',likely:'likelyScoreLabel',scoreline:'scorelineTitle',explain:'scoreExplanation',how:'howTitle',toggle:'languageToggle',s1:'search1Label',s2:'search2Label'};for(const k in ids){const el=$('#'+ids[k]);if(el)el.textContent=t[k]}$('#homeSearch').placeholder=t.ph;$('#awaySearch').placeholder=t.ph;$('#venue').options[0].textContent=t.neutral;$('#venue').options[1].textContent=t.home;$('#venue').options[2].textContent=t.away;rebuild()}
function search(input,select){const q=input.value.toLowerCase();for(const o of select.options)o.hidden=!!q&&!o.value.toLowerCase().includes(q)&&!o.textContent.toLowerCase().includes(q)}
$('#languageToggle').onclick=()=>{lang=lang==='en'?'zh':'en';setText()};home.onchange=sync;away.onchange=sync;venue.onchange=analyze;homeElo.oninput=analyze;awayElo.oninput=analyze;$('#analyze').onclick=analyze;$('#homeSearch').oninput=e=>search(e.target,home);$('#awaySearch').oninput=e=>search(e.target,away);$('#competitionMode')?.addEventListener('change',analyze);
async function load(){try{const r=await fetch('ratings.json?'+Date.now(),{cache:'no-store'});const d=await r.json();if(Array.isArray(d.teams))teams=Object.fromEntries(d.teams.map(x=>[normalize(x.team),Number(x.elo)]));$('#dataStatus').textContent=lang==='zh'?`已加载实时评分 · ${Object.keys(teams).length} 支球队`:`Live ratings loaded · ${Object.keys(teams).length} teams`}catch(e){teams={...fallback};$('#dataStatus').textContent=lang==='zh'?'正在使用备用评分':'Using fallback ratings'}rebuild();try{const r=await fetch('team-stats.json?'+Date.now(),{cache:'no-store'});if(r.ok)stats=await r.json()}catch(e){}analyze()}
setText();load();