// Phase 2.4 — 48-team World Cup simulator + Monte Carlo stats
const WC26_TEAMS=['Canada','Mexico','United States','Australia','Iraq','Iran','Japan','Jordan','South Korea','Qatar','Saudi Arabia','Uzbekistan','Algeria','Cabo Verde','DR Congo','Côte d’Ivoire','Egypt','Ghana','Morocco','Senegal','South Africa','Tunisia','Curaçao','Haiti','Panama','Argentina','Brazil','Colombia','Ecuador','Paraguay','Uruguay','New Zealand','Austria','Belgium','Bosnia and Herzegovina','Croatia','Czechia','England','France','Germany','Netherlands','Norway','Portugal','Scotland','Spain','Sweden','Switzerland','Türkiye'];
const $t=s=>document.querySelector(s);let tournamentTeams=Object.fromEntries(WC26_TEAMS.map(t=>[t,1500]));
function rng(){return Math.random()}
function poisson(lambda){lambda=Math.max(0.01,Number(lambda)||0.01);const L=Math.exp(-lambda);let k=0,p=1;do{k++;p*=rng()}while(p>L);return k-1}
function teamProfile(name){return{elo:Number(tournamentTeams[name]??1500)}}
function simulate90(a,b){if(!a||!b)throw new Error(`Invalid teams: ${a} vs ${b}`);if(!window.SoccerModel?.predictMatch)throw new Error('Soccer model did not load');const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');return{a,b,ga:poisson(p.expectedGoals.team1),gb:poisson(p.expectedGoals.team2),xg1:p.expectedGoals.team1,xg2:p.expectedGoals.team2}}
function penaltyResult(a,b){let aK=0,bK=0;for(let round=1;round<=5;round++){if(rng()<0.75)aK++;if(rng()<0.75)bK++}while(aK===bK){if(rng()<0.75)aK++;if(rng()<0.75)bK++}return{winner:aK>bK?a:b,score:`${aK}–${bK}`,aK,bK}}
function knockoutMatch(a,b){let m=simulate90(a,b);m.regulationGa=m.ga;m.regulationGb=m.gb;if(m.ga===m.gb){const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');m.ga+=poisson(p.expectedGoals.team1/3);m.gb+=poisson(p.expectedGoals.team2/3);m.extra=true;m.extraGa=m.ga;m.extraGb=m.gb;if(m.ga===m.gb){const pen=penaltyResult(a,b);m.penalties=true;m.penaltyWinner=pen.winner;m.penaltyScore=pen.score}}m.winner=m.ga>m.gb?a:m.gb>m.ga?b:m.penaltyWinner;return m}
function makeGroups(){const ranked=WC26_TEAMS.slice().sort((a,b)=>tournamentTeams[b]-tournamentTeams[a]);const pots=[ranked.slice(0,12),ranked.slice(12,24),ranked.slice(24,36),ranked.slice(36,48)];for(const p of pots)for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}const groups=Array.from({length:12},()=>[]);for(const p of pots)for(let i=0;i<12;i++)groups[i].push(p[i]);return groups}
function standingsFor(group,matches){const rows=Object.fromEntries(group.map(t=>[t,{team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0}]));for(const m of matches){const x=rows[m.a],y=rows[m.b];x.gf+=m.ga;x.ga+=m.gb;y.gf+=m.gb;y.ga+=m.ga;x.gd=x.gf-x.ga;y.gd=y.gf-y.ga;if(m.ga>m.gb){x.p+=3;x.w++;y.l++}else if(m.gb>m.ga){y.p+=3;y.w++;x.l++}else{x.p++;y.p++;x.d++;y.d++}}return Object.values(rows).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team])}
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function groupCard(i,g,matches,table){const letter=String.fromCharCode(65+i);let html=`<section class="card wc-group wc-stage" data-stage="group-${letter}"><h3>Group ${letter}</h3><table class="wc-table"><thead><tr><th>Team</th><th>Pts</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th></tr></thead><tbody>`;for(const r of table)html+=`<tr><th>${esc(r.team)}</th><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd}</td></tr>`;html+='</tbody></table><h4>Matches</h4><div class="match-list">';for(const m of matches)html+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${m.ga}–${m.gb}</strong><span>${esc(m.b)}</span></div>`;return html+'</div></section>'}
function bracketRound(title,pairs){const stage=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let html=`<section class="card wc-stage" data-stage="${stage}"><h3>${title}</h3><div class="knockout-list">`;for(const m of pairs){let score=`${m.regulationGa}–${m.regulationGb}`;if(m.extra)score+=` <small>(ET: ${m.extraGa}–${m.extraGb})</small>`;if(m.penalties)score+=` <small>(P: ${m.penaltyScore})</small>`;html+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${score}</strong><span>${esc(m.b)}</span></div>`}return html+'</div></section>'}
function setupStageNavigation(){const results=$t('#tournamentResults');let nav=$t('#wcStageNav');if(!nav){nav=document.createElement('div');nav.id='wcStageNav';nav.className='wc-stage-nav';results.parentNode.insertBefore(nav,results)}const stages=[...results.querySelectorAll('.wc-stage')];nav.innerHTML=stages.map(s=>`<button type="button" class="wc-stage-button" data-stage-target="${s.dataset.stage}">${s.querySelector('h3').textContent}</button>`).join('');const buttons=[...nav.querySelectorAll('.wc-stage-button')];function showStage(target){stages.forEach(s=>s.hidden=s.dataset.stage!==target);buttons.forEach(b=>b.classList.toggle('active',b.dataset.stageTarget===target));results.querySelector('.wc-summary')?.setAttribute('hidden','hidden')}buttons.forEach(b=>b.onclick=()=>showStage(b.dataset.stageTarget));if(buttons.length)showStage(buttons[0].dataset.stageTarget);nav.hidden=false}
function simulateTournament(){const groups=makeGroups(),allGroupMatches=[],groupTables=[];groups.forEach(g=>{const ms=[];for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)ms.push(simulate90(g[i],g[j]));allGroupMatches.push(ms);groupTables.push(standingsFor(g,ms))});const qualified=[];groupTables.forEach(t=>qualified.push(t[0].team,t[1].team));const thirds=groupTables.map(t=>t[2]).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team]);qualified.push(...thirds.slice(0,8).map(r=>r.team));const stageTeams={round32:[...qualified],round16:[],quarterfinals:[],semifinals:[],final:[],champion:null};let knockout=qualified.slice();const rounds=[];let roundName='Round of 32';while(knockout.length>1){const pairs=[],winners=[];for(let i=0;i<knockout.length;i+=2){const m=knockoutMatch(knockout[i],knockout[i+1]);pairs.push(m);winners.push(m.winner)}rounds.push({title:roundName,pairs});knockout=winners;if(roundName==='Round of 32')stageTeams.round16=[...knockout];else if(roundName==='Round of 16')stageTeams.quarterfinals=[...knockout];else if(roundName==='Quarter-finals')stageTeams.semifinals=[...knockout];else if(roundName==='Semi-finals')stageTeams.final=[...knockout];if(knockout.length===16)roundName='Round of 16';else if(knockout.length===8)roundName='Quarter-finals';else if(knockout.length===4)roundName='Semi-finals';else if(knockout.length===2)roundName='Final'}stageTeams.champion=knockout[0]||null;return{groups,allGroupMatches,groupTables,rounds,stageTeams}}
function runTournament(){const results=$t('#tournamentResults'),status=$t('#tournamentStatus');status.textContent='Running…';try{const data=simulateTournament();let html='<div class="wc-summary card"><h2>Simulation complete</h2><p>12 groups were drawn automatically from four Elo pots. The top two in each group plus the eight best third-place teams advanced to the Round of 32.</p><p><strong>Champion:</strong> '+esc(data.stageTeams.champion||'—')+'</p></div>';data.groups.forEach((g,i)=>html+=groupCard(i,g,data.allGroupMatches[i],data.groupTables[i]));for(const r of data.rounds)html+=bracketRound(r.title,r.pairs);results.innerHTML=html;results.hidden=false;setupStageNavigation();status.textContent='1 simulation complete.';results.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error('World Cup simulation failed:',e);status.textContent='Simulation error: '+(e.message||'unknown error')}}
function pct(value,total){return total?((value/total)*100).toFixed(1)+'%':'0.0%'}
function renderStats(stats,count){const rows=Object.values(stats).sort((a,b)=>b.champion-a.champion||b.final-a.final||b.semifinals-a.semifinals||b.quarterfinals-a.quarterfinals||b.round16-a.round16||b.round32-a.round32);let html=`<section class="card"><h2>Results from ${count.toLocaleString()} simulations</h2><p class="muted">Percentages show the share of simulations in which a team reached each stage.</p><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Team</th><th>Round of 32</th><th>Round of 16</th><th>Quarter-finals</th><th>Semi-finals</th><th>Final</th><th>Champion</th></tr></thead><tbody>`;for(const r of rows)html+=`<tr><th>${esc(r.team)}</th><td>${pct(r.round32,count)}</td><td>${pct(r.round16,count)}</td><td>${pct(r.quarterfinals,count)}</td><td>${pct(r.final,count)}</td><td>${pct(r.champion,count)}</td></tr>`;return html+'</tbody></table></div></section>'}
function runManySimulations(){const input=$t('#simulationCount'),button=$t('#runManySimulations'),status=$t('#statsStatus'),output=$t('#simulationStats');let count=Math.floor(Number(input.value)||1000);count=Math.max(10,Math.min(10000,count));input.value=count;button.disabled=true;output.hidden=true;let stats=Object.fromEntries(WC26_TEAMS.map(t=>[t,{team:t,round32:0,round16:0,quarterfinals:0,semifinals:0,final:0,champion:0}]));let done=0;const batchSize=10;const batch=()=>{try{const end=Math.min(done+batchSize,count);for(;done<end;done++){const result=simulateTournament().stageTeams;result.round32.forEach(t=>stats[t].round32++);result.round16.forEach(t=>stats[t].round16++);result.quarterfinals.forEach(t=>stats[t].quarterfinals++);result.semifinals.forEach(t=>stats[t].semifinals++);result.final.forEach(t=>stats[t].final++);if(result.champion)stats[result.champion].champion++}status.textContent=`Running ${done.toLocaleString()}/${count.toLocaleString()}…`;if(done<count){setTimeout(batch,0);return}output.innerHTML=renderStats(stats,count);output.hidden=false;status.textContent=`Finished — ${count.toLocaleString()} simulations.`;button.disabled=false}catch(e){console.error('Monte Carlo simulation failed:',e);status.textContent='Simulation error: '+(e.message||'unknown error');button.disabled=false}};status.textContent=`Running 0/${count.toLocaleString()}…`;setTimeout(batch,0)}
async function loadTournamentTeams(){try{const r=await fetch('ratings.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(`ratings.json HTTP ${r.status}`);const d=await r.json();if(Array.isArray(d.teams))for(const x of d.teams){const n=String(x.team||'').trim();const canonical=n==='DR Congo'||n==='Democratic Republic of the Congo'?'DR Congo':n==='Côte d’Ivoire'||n==="Côte d'Ivoire"?'Côte d’Ivoire':n==='Korea Republic'?'South Korea':n==='IR Iran'?'Iran':n==='USA'?'United States':n;if(WC26_TEAMS.includes(canonical))tournamentTeams[canonical]=Number(x.elo)||1500}}catch(e){console.warn('Could not load ratings; using Elo 1500 fallback:',e)}$t('#tournamentStatus').textContent=`Ready — ${WC26_TEAMS.length} teams available.`}
function initTournament(){const matchTab=$t('#matchTab'),tourTab=$t('#tournamentTab'),statsTab=$t('#statsTab'),matchPage=$t('#matchPage'),tourPage=$t('#tournamentPage'),statsPage=$t('#statsPage');function showPage(page,tab){[matchTab,tourTab,statsTab].forEach(t=>t.classList.remove('active'));[matchPage,tourPage,statsPage].forEach(p=>p.hidden=true);tab.classList.add('active');page.hidden=false}matchTab.onclick=()=>showPage(matchPage,matchTab);tourTab.onclick=()=>showPage(tourPage,tourTab);statsTab.onclick=()=>showPage(statsPage,statsTab);$t('#runTournament').onclick=runTournament;$t('#runManySimulations').onclick=runManySimulations;loadTournamentTeams()}
initTournament();

// Competition support for Simulation Stats: World Cup, UEFA EURO and Copa América.
const EURO_TEAMS=['Albania','Austria','Belgium','Croatia','Czechia','Denmark','England','France','Georgia','Germany','Hungary','Italy','Netherlands','Poland','Portugal','Romania','Scotland','Serbia','Slovakia','Slovenia','Spain','Switzerland','Türkiye','Ukraine'];
const COPA_TEAMS=['Argentina','Bolivia','Brazil','Canada','Chile','Colombia','Costa Rica','Ecuador','Jamaica','Mexico','Panama','Paraguay','Peru','United States','Uruguay','Venezuela'];
const ALL_COMP_TEAMS=[...new Set([...WC26_TEAMS,...EURO_TEAMS,...COPA_TEAMS])];
ALL_COMP_TEAMS.forEach(t=>{if(!(t in tournamentTeams))tournamentTeams[t]=1500});
const COMPETITIONS={worldcup:{name:'World Cup',teams:WC26_TEAMS,thirdsToAdvance:8,statsStages:[['round32','Round of 32'],['round16','Round of 16'],['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]},euro:{name:'European Championship (EURO)',teams:EURO_TEAMS,thirdsToAdvance:4,statsStages:[['round16','Round of 16'],['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]},copa:{name:'Copa América',teams:COPA_TEAMS,thirdsToAdvance:0,statsStages:[['quarterfinals','Quarter-finals'],['semifinals','Semi-finals'],['final','Final'],['champion','Champion']]}};
function competitionGroups(c){const ranked=c.teams.slice().sort((a,b)=>tournamentTeams[b]-tournamentTeams[a]);const groups=Array.from({length:c.teams.length/4},()=>[]);const pots=[ranked.slice(0,groups.length),ranked.slice(groups.length,groups.length*2),ranked.slice(groups.length*2,groups.length*3),ranked.slice(groups.length*3)];for(const p of pots){for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}for(let i=0;i<groups.length;i++)groups[i].push(p[i])}return groups}
function simulateCompetition(c){const groups=competitionGroups(c),tables=[];for(const g of groups){const ms=[];for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)ms.push(simulate90(g[i],g[j]));tables.push(standingsFor(g,ms))}let qualified=[];tables.forEach(t=>qualified.push(t[0].team,t[1].team));if(c.thirdsToAdvance){qualified.push(...tables.map(t=>t[2]).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team]).slice(0,c.thirdsToAdvance).map(r=>r.team))}const stageTeams={round32:[],round16:[],quarterfinals:[],semifinals:[],final:[],champion:null};if(c===COMPETITIONS.worldcup)stageTeams.round32=[...qualified];if(qualified.length===16)stageTeams.round16=[...qualified];if(qualified.length===8)stageTeams.quarterfinals=[...qualified];let knockout=qualified.slice();while(knockout.length>1){const winners=[];for(let i=0;i<knockout.length;i+=2)winners.push(knockoutMatch(knockout[i],knockout[i+1]).winner);knockout=winners;if(knockout.length===16)stageTeams.round16=[...knockout];else if(knockout.length===8)stageTeams.quarterfinals=[...knockout];else if(knockout.length===4)stageTeams.semifinals=[...knockout];else if(knockout.length===2)stageTeams.final=[...knockout]}stageTeams.champion=knockout[0]||null;return{stageTeams}}
function setupCompetitionSelector(){const anchor=$t('#simulationCount');if(!anchor||$t('#competitionType'))return;const wrap=document.createElement('div');wrap.className='competition-selector';wrap.style.marginBottom='12px';wrap.innerHTML='<label for="competitionType"><strong>Competition:</strong> </label><select id="competitionType"><option value="worldcup">World Cup</option><option value="euro">European Championship (EURO)</option><option value="copa">Copa América</option></select>';anchor.parentNode.insertBefore(wrap,anchor)}
setupCompetitionSelector();
function runManySimulations(){const input=$t('#simulationCount'),button=$t('#runManySimulations'),status=$t('#statsStatus'),output=$t('#simulationStats');setupCompetitionSelector();let count=Math.floor(Number(input.value)||1000);count=Math.max(10,Math.min(10000,count));input.value=count;button.disabled=true;output.hidden=true;const c=COMPETITIONS[$t('#competitionType')?.value||'worldcup'];const stats=Object.fromEntries(c.teams.map(t=>[t,{team:t,round32:0,round16:0,quarterfinals:0,semifinals:0,final:0,champion:0}]));let done=0;const batch=()=>{try{const end=Math.min(done+10,count);for(;done<end;done++){const result=simulateCompetition(c).stageTeams;Object.keys(stats).forEach(t=>{if(result.round32.includes(t))stats[t].round32++;if(result.round16.includes(t))stats[t].round16++;if(result.quarterfinals.includes(t))stats[t].quarterfinals++;if(result.semifinals.includes(t))stats[t].semifinals++;if(result.final.includes(t))stats[t].final++;if(result.champion===t)stats[t].champion++})}status.textContent=`Running ${done.toLocaleString()}/${count.toLocaleString()}…`;if(done<count){setTimeout(batch,0);return}const rows=Object.values(stats).sort((a,b)=>b.champion-a.champion||b.final-a.final||b.semifinals-a.semifinals||b.quarterfinals-a.quarterfinals||b.round16-a.round16||b.round32-a.round32);const stages=c.statsStages;let html=`<section class="card"><h2>${esc(c.name)} — Results from ${count.toLocaleString()} simulations</h2><p class="muted">Percentages show how often each team reached each stage.</p><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Team</th>${stages.map(s=>`<th>${esc(s[1])}</th>`).join('')}</tr></thead><tbody>`;for(const r of rows)html+=`<tr><th>${esc(r.team)}</th>${stages.map(s=>`<td>${pct(r[s[0]],count)}</td>`).join('')}</tr>`;html+='</tbody></table></div></section>';output.innerHTML=html;output.hidden=false;status.textContent=`Finished — ${count.toLocaleString()} ${c.name} simulations.`;button.disabled=false}catch(e){console.error('Monte Carlo simulation failed:',e);status.textContent='Simulation error: '+(e.message||'unknown error');button.disabled=false}};status.textContent=`Running 0/${count.toLocaleString()}…`;setTimeout(batch,0)}