// Phase 2.1 — one-run 48-team World Cup simulator
const WC26_TEAMS=['Canada','Mexico','United States','Australia','Iraq','Iran','Japan','Jordan','South Korea','Qatar','Saudi Arabia','Uzbekistan','Algeria','Cabo Verde','DR Congo','Côte d’Ivoire','Egypt','Ghana','Morocco','Senegal','South Africa','Tunisia','Curaçao','Haiti','Panama','Argentina','Brazil','Colombia','Ecuador','Paraguay','Uruguay','New Zealand','Austria','Belgium','Bosnia and Herzegovina','Croatia','Czechia','England','France','Germany','Netherlands','Norway','Portugal','Scotland','Spain','Sweden','Switzerland','Türkiye'];
const $t=s=>document.querySelector(s);let tournamentTeams={};
function rng(){return Math.random()}
function poisson(lambda){const L=Math.exp(-lambda);let k=0,p=1;do{k++;p*=rng()}while(p>L);return k-1}
function teamProfile(name){return{elo:Number(tournamentTeams[name]??1500)}}
function simulate90(a,b){const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');return{a,b,ga:poisson(p.expectedGoals.team1),gb:poisson(p.expectedGoals.team2),xg1:p.expectedGoals.team1,xg2:p.expectedGoals.team2}}
function knockoutMatch(a,b){let m=simulate90(a,b);if(m.ga===m.gb){const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');m.ga+=poisson(p.expectedGoals.team1/3);m.gb+=poisson(p.expectedGoals.team2/3);m.extra=true;if(m.ga===m.gb){const winner=rng()<0.5?a:b;m.penalties=true;m.penaltyWinner=winner;}}m.winner=m.ga>m.gb?a:m.gb>m.ga?b:m.penaltyWinner;return m}
function makeGroups(){const ranked=Object.entries(tournamentTeams).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);const pots=[ranked.slice(0,12),ranked.slice(12,24),ranked.slice(24,36),ranked.slice(36,48)];for(const p of pots)for(let i=p.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[p[i],p[j]]=[p[j],p[i]]}const groups=Array.from({length:12},()=>[]);for(const p of pots)for(let i=0;i<12;i++)groups[i].push(p[i]);return groups}
function standingsFor(group,matches){const rows=Object.fromEntries(group.map(t=>[t,{team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0}]));for(const m of matches){const x=rows[m.a],y=rows[m.b];x.gf+=m.ga;x.ga+=m.gb;y.gf+=m.gb;y.ga+=m.ga;x.gd=x.gf-x.ga;y.gd=y.gf-y.ga;if(m.ga>m.gb){x.p+=3;x.w++;y.l++}else if(m.gb>m.ga){y.p+=3;y.w++;x.l++}else{x.p++;y.p++;x.d++;y.d++}}return Object.values(rows).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team])}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function groupCard(i,g,matches,table){const letter=String.fromCharCode(65+i);let html=`<section class="card wc-group"><h3>Group ${letter}</h3><table class="wc-table"><thead><tr><th>Team</th><th>Pts</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th></tr></thead><tbody>`;for(const r of table)html+=`<tr><th>${esc(r.team)}</th><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd}</td></tr>`;html+='</tbody></table><h4>Matches</h4><div class="match-list">';for(const m of matches)html+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${m.ga}–${m.gb}</strong><span>${esc(m.b)}</span></div>`;return html+'</div></section>'}
function bracketRound(title,pairs){let html=`<section class="card"><h3>${title}</h3><div class="knockout-list">`;for(const m of pairs)html+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${m.ga}–${m.gb}${m.penalties?' (P)':''}</strong><span>${esc(m.b)}</span></div>`;return html+'</div></section>'}
function runTournament(){const results=$t('#tournamentResults'),status=$t('#tournamentStatus');status.textContent='Running…';const groups=makeGroups(),allGroupMatches=[],groupTables=[];groups.forEach(g=>{const ms=[];for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)ms.push(simulate90(g[i],g[j]));allGroupMatches.push(ms);groupTables.push(standingsFor(g,ms))});const qualified=[];groupTables.forEach(t=>{qualified.push(t[0].team,t[1].team)});const thirds=groupTables.map(t=>t[2]).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team]);qualified.push(...thirds.slice(0,8).map(r=>r.team));let knockout=qualified.slice();const rounds=[];let roundName='Round of 32';while(knockout.length>1){const pairs=[];const winners=[];for(let i=0;i<knockout.length;i+=2){const m=knockoutMatch(knockout[i],knockout[i+1]);pairs.push(m);winners.push(m.winner)}rounds.push({title:roundName,pairs});knockout=winners;if(knockout.length===16)roundName='Round of 16';else if(knockout.length===8)roundName='Quarter-finals';else if(knockout.length===4)roundName='Semi-finals';else if(knockout.length===2)roundName='Final'}let html='<div class="wc-summary card"><h2>Simulation complete</h2><p>12 groups were drawn automatically from four Elo pots. The top two in each group plus the eight best third-place teams advanced to the Round of 32.</p><p><strong>Champion:</strong> '+esc(knockout[0]||'—')+'</p></div>';groups.forEach((g,i)=>html+=groupCard(i,g,allGroupMatches[i],groupTables[i]));for(const r of rounds)html+=bracketRound(r.title,r.pairs);results.innerHTML=html;results.hidden=false;status.textContent='1 simulation complete.';results.scrollIntoView({behavior:'smooth',block:'start'})}
async function loadTournamentTeams(){try{const r=await fetch('ratings.json?'+Date.now(),{cache:'no-store'});const d=await r.json();if(Array.isArray(d.teams))for(const x of d.teams){const n=String(x.team||'').trim();const canonical=n==='DR Congo'||n==='Democratic Republic of the Congo'?'DR Congo':n==='Côte d’Ivoire'||n==="Côte d'Ivoire"?"Côte d'Ivoire":n==='Korea Republic'?'South Korea':n==='IR Iran'?'Iran':n==='USA'?'United States':n;tournamentTeams[canonical]=Number(x.elo)}}catch(e){}for(const t of WC26_TEAMS)if(!(t in tournamentTeams))tournamentTeams[t]=1500;$t('#tournamentStatus').textContent=`Ready — ${Object.keys(tournamentTeams).length} teams available.`}
function initTournament(){const matchTab=$t('#matchTab'),tourTab=$t('#tournamentTab'),matchPage=$t('#matchPage'),tourPage=$t('#tournamentPage');matchTab.onclick=()=>{matchTab.classList.add('active');tourTab.classList.remove('active');matchPage.hidden=false;tourPage.hidden=true};tourTab.onclick=()=>{tourTab.classList.add('active');matchTab.classList.remove('active');matchPage.hidden=true;tourPage.hidden=false};$t('#runTournament').onclick=runTournament;loadTournamentTeams()}
initTournament();