// World Cup simulator — supports 2026 and projected 2030
const WC26_TEAMS=['Canada','Mexico','United States','Australia','Iraq','Iran','Japan','Jordan','South Korea','Qatar','Saudi Arabia','Uzbekistan','Algeria','Cabo Verde','DR Congo','Côte d’Ivoire','Egypt','Ghana','Morocco','Senegal','South Africa','Tunisia','Curaçao','Haiti','Panama','Argentina','Brazil','Colombia','Ecuador','Paraguay','Uruguay','New Zealand','Austria','Belgium','Bosnia and Herzegovina','Croatia','Czechia','England','France','Germany','Netherlands','Norway','Portugal','Scotland','Spain','Sweden','Switzerland','Türkiye'];
const WC2030_HOSTS=['Spain','Portugal','Morocco','Argentina','Paraguay','Uruguay'];
const CONFIG={2026:{teams:WC26_TEAMS,hosts:['Canada','Mexico','United States'],projected:false},2030:{teams:WC26_TEAMS,hosts:WC2030_HOSTS,projected:true}};
const $t=s=>document.querySelector(s);let selectedYear=2026;let tournamentTeams=Object.fromEntries(WC26_TEAMS.map(t=>[t,1500]));
function activeTeams(){return CONFIG[selectedYear].teams} function rng(){return Math.random()}
function poisson(lambda){lambda=Math.max(.01,Number(lambda)||.01);const L=Math.exp(-lambda);let k=0,p=1;do{k++;p*=rng()}while(p>L);return k-1}
function teamProfile(name){return{elo:Number(tournamentTeams[name]??1500)}}
function simulate90(a,b){const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');return{a,b,ga:poisson(p.expectedGoals.team1),gb:poisson(p.expectedGoals.team2)}}
function penaltyResult(a,b){let aK=0,bK=0;for(let r=1;r<=5;r++){if(rng()<.75)aK++;if(rng()<.75)bK++}while(aK===bK){if(rng()<.75)aK++;if(rng()<.75)bK++}return{winner:aK>bK?a:b,score:`${aK}–${bK}`}}
function knockoutMatch(a,b){const m=simulate90(a,b);m.regulationGa=m.ga;m.regulationGb=m.gb;if(m.ga===m.gb){const p=window.SoccerModel.predictMatch(teamProfile(a),teamProfile(b),'neutral');m.ga+=poisson(p.expectedGoals.team1/3);m.gb+=poisson(p.expectedGoals.team2/3);m.extra=true;m.extraGa=m.ga;m.extraGb=m.gb;if(m.ga===m.gb){const pen=penaltyResult(a,b);m.penalties=true;m.penaltyWinner=pen.winner;m.penaltyScore=pen.score}}m.winner=m.ga>m.gb?a:m.gb>m.ga?b:m.penaltyWinner;return m}
function makeGroups(){const ranked=activeTeams().slice().sort((a,b)=>tournamentTeams[b]-tournamentTeams[a]);const pots=[ranked.slice(0,12),ranked.slice(12,24),ranked.slice(24,36),ranked.slice(36,48)];for(const p of pots)for(let i=p.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[p[i],p[j]]=[p[j],p[i]]}const groups=Array.from({length:12},()=>[]);for(const p of pots)for(let i=0;i<12;i++)groups[i].push(p[i]);return groups}
function standingsFor(group,matches){const rows=Object.fromEntries(group.map(t=>[t,{team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0}]));for(const m of matches){const x=rows[m.a],y=rows[m.b];x.gf+=m.ga;x.ga+=m.gb;y.gf+=m.gb;y.ga+=m.ga;x.gd=x.gf-x.ga;y.gd=y.gf-y.ga;if(m.ga>m.gb){x.p+=3;x.w++;y.l++}else if(m.gb>m.ga){y.p+=3;y.w++;x.l++}else{x.p++;y.p++;x.d++;y.d++}}return Object.values(rows).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team])}
function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function groupCard(i,matches,table){const letter=String.fromCharCode(65+i);let h=`<section class="card wc-group wc-stage" data-stage="group-${letter}"><h3>Group ${letter}</h3><table class="wc-table"><thead><tr><th>Team</th><th>Pts</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th></tr></thead><tbody>`;for(const r of table)h+=`<tr><th>${esc(r.team)}</th><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd}</td></tr>`;h+='</tbody></table><h4>Matches</h4><div class="match-list">';for(const m of matches)h+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${m.ga}–${m.gb}</strong><span>${esc(m.b)}</span></div>`;return h+'</div></section>'}
function bracketRound(title,pairs){const stage=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let h=`<section class="card wc-stage" data-stage="${stage}"><h3>${title}</h3><div class="knockout-list">`;for(const m of pairs){let s=`${m.regulationGa}–${m.regulationGb}`;if(m.extra)s+=` <small>(ET: ${m.extraGa}–${m.extraGb})</small>`;if(m.penalties)s+=` <small>(P: ${m.penaltyScore})</small>`;h+=`<div class="match-row"><span>${esc(m.a)}</span><strong>${s}</strong><span>${esc(m.b)}</span></div>`}return h+'</div></section>'}
function setupStageNavigation(){const results=$t('#tournamentResults');let nav=$t('#wcStageNav');if(!nav){nav=document.createElement('div');nav.id='wcStageNav';nav.className='wc-stage-nav';results.parentNode.insertBefore(nav,results)}const stages=[...results.querySelectorAll('.wc-stage')];nav.innerHTML=stages.map(s=>`<button type="button" class="wc-stage-button" data-stage-target="${s.dataset.stage}">${s.querySelector('h3').textContent}</button>`).join('');const buttons=[...nav.querySelectorAll('.wc-stage-button')];function showStage(target){stages.forEach(s=>s.hidden=s.dataset.stage!==target);buttons.forEach(b=>b.classList.toggle('active',b.dataset.stageTarget===target))}buttons.forEach(b=>b.onclick=()=>showStage(b.dataset.stageTarget));if(buttons.length)showStage(buttons[0].dataset.stageTarget);nav.hidden=false}
function simulateTournament(){const groups=makeGroups(),all=[],tables=[];groups.forEach(g=>{const ms=[];for(let i=0;i<4;i++)for(let j=i+1;j<4;j++)ms.push(simulate90(g[i],g[j]));all.push(ms);tables.push(standingsFor(g,ms))});const q=[];tables.forEach(t=>q.push(t[0].team,t[1].team));q.push(...tables.map(t=>t[2]).sort((a,b)=>b.p-a.p||b.gd-a.gd||b.gf-a.gf||tournamentTeams[b.team]-tournamentTeams[a.team]).slice(0,8).map(r=>r.team));const stageTeams={round32:[...q],round16:[],quarterfinals:[],semifinals:[],final:[],champion:null};let k=q.slice(),rounds=[],name='Round of 32';while(k.length>1){const pairs=[],w=[];for(let i=0;i<k.length;i+=2){const m=knockoutMatch(k[i],k[i+1]);pairs.push(m);w.push(m.winner)}rounds.push({title:name,pairs});k=w;if(name==='Round of 32')stageTeams.round16=[...k];else if(name==='Round of 16')stageTeams.quarterfinals=[...k];else if(name==='Quarter-finals')stageTeams.semifinals=[...k];else if(name==='Semi-finals')stageTeams.final=[...k];if(k.length===16)name='Round of 16';else if(k.length===8)name='Quarter-finals';else if(k.length===4)name='Semi-finals';else if(k.length===2)name='Final'}stageTeams.champion=k[0]||null;return{groups,allGroupMatches:all,groupTables:tables,rounds,stageTeams}}
function runTournament(){const results=$t('#tournamentResults'),status=$t('#tournamentStatus');status.textContent='Running…';try{const d=simulateTournament(),cfg=CONFIG[selectedYear];let h=`<div class="wc-summary card"><h2>${selectedYear} simulation complete</h2><p>12 groups of four were drawn automatically from four Elo pots. The top two in each group plus the eight best third-place teams advanced to the Round of 32.</p><p><strong>${selectedYear} champion:</strong> ${esc(d.stageTeams.champion||'—')}</p>${selectedYear===2030?`<p><strong>2030 hosts/centenary participants:</strong> ${cfg.hosts.map(esc).join(', ')}</p>`:''}</div>`;d.groups.forEach((g,i)=>h+=groupCard(i,d.allGroupMatches[i],d.groupTables[i]));d.rounds.forEach(r=>h+=bracketRound(r.title,r.pairs));results.innerHTML=h;results.hidden=false;setupStageNavigation();status.textContent=`${selectedYear}: 1 simulation complete.`;results.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error(e);status.textContent='Simulation error: '+(e.message||'unknown error')}}
function pct(v,n){return n?((v/n)*100).toFixed(1)+'%':'0.0%'}
function renderStats(stats,count){const rows=Object.values(stats).sort((a,b)=>b.champion-a.champion||b.final-a.final||b.semifinals-a.semifinals||b.quarterfinals-a.quarterfinals||b.round16-a.round16||b.round32-a.round32);let h=`<section class="card"><h2>${selectedYear} — Results from ${count.toLocaleString()} simulations</h2><p class="muted">Percentages show the share of simulations in which a team reached each stage.</p><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Team</th><th>Round of 32</th><th>Round of 16</th><th>Quarter-finals</th><th>Semi-finals</th><th>Final</th><th>Champion</th></tr></thead><tbody>`;for(const r of rows)h+=`<tr><th>${esc(r.team)}</th><td>${pct(r.round32,count)}</td><td>${pct(r.round16,count)}</td><td>${pct(r.quarterfinals,count)}</td><td>${pct(r.semifinals,count)}</td><td>${pct(r.final,count)}</td><td><strong>${pct(r.champion,count)}</strong></td></tr>`;return h+'</tbody></table></div></section>'}
function runManySimulations(){const input=$t('#simulationCount'),button=$t('#runManySimulations'),status=$t('#statsStatus'),output=$t('#simulationStats');let count=Math.floor(Number(input.value)||1000);count=Math.max(10,Math.min(10000,count));input.value=count;button.disabled=true;output.hidden=true;const teams=activeTeams();let stats=Object.fromEntries(teams.map(t=>[t,{team:t,round32:0,round16:0,quarterfinals:0,semifinals:0,final:0,champion:0}]));let done=0;const batch=()=>{try{const end=Math.min(done+10,count);for(;done<end;done++){const r=simulateTournament().stageTeams;r.round32.forEach(t=>stats[t].round32++);r.round16.forEach(t=>stats[t].round16++);r.quarterfinals.forEach(t=>stats[t].quarterfinals++);r.semifinals.forEach(t=>stats[t].semifinals++);r.final.forEach(t=>stats[t].final++);if(r.champion)stats[r.champion].champion++}status.textContent=`${selectedYear}: ${done.toLocaleString()}/${count.toLocaleString()}…`;if(done<count){setTimeout(batch,0);return}output.innerHTML=renderStats(stats,count);output.hidden=false;status.textContent=`${selectedYear}: finished ${count.toLocaleString()} simulations.`;button.disabled=false}catch(e){console.error(e);status.textContent='Simulation error: '+(e.message||'unknown error');button.disabled=false}};status.textContent=`${selectedYear}: running 0/${count.toLocaleString()}…`;setTimeout(batch,0)}
async function loadTournamentTeams(){try{const r=await fetch('ratings.json?'+Date.now(),{cache:'no-store'});const d=await r.json();if(Array.isArray(d.teams))for(const x of d.teams){const n=String(x.team||'').trim();const c=n==='DR Congo'||n==='Democratic Republic of the Congo'?'DR Congo':n==='Côte d’Ivoire'||n==="Côte d'Ivoire"?'Côte d’Ivoire':n==='Korea Republic'?'South Korea':n==='IR Iran'?'Iran':n==='USA'?'United States':n;if(WC26_TEAMS.includes(c))tournamentTeams[c]=Number(x.elo)||1500}}catch(e){console.warn('Ratings unavailable; using Elo 1500 fallback')}updateYearUI()}
function updateYearUI(){selectedYear=Number($t('#wcYear').value);$t('#wc2030Note').hidden=selectedYear!==2030;$t('#tournamentStatus').textContent=`Ready — ${selectedYear}: ${activeTeams().length} teams configured.`}
function updateStatsYear(){selectedYear=Number($t('#statsWorldCupYear').value);$t('#stats2030Note').hidden=selectedYear!==2030;$t('#statsStatus').textContent=`Ready — ${selectedYear}: ${activeTeams().length} teams configured.`;$t('#simulationStats').hidden=true}
function initTournament(){const mt=$t('#matchTab'),tt=$t('#tournamentTab'),st=$t('#statsTab'),mp=$t('#matchPage'),tp=$t('#tournamentPage'),sp=$t('#statsPage');function show(p,t){[mt,tt,st].forEach(x=>x.classList.remove('active'));[mp,tp,sp].forEach(x=>x.hidden=true);t.classList.add('active');p.hidden=false}mt.onclick=()=>show(mp,mt);tt.onclick=()=>show(tp,tt);st.onclick=()=>{show(sp,st);updateStatsYear()};$t('#wcYear').onchange=()=>{updateYearUI();$t('#tournamentResults').hidden=true};$t('#statsWorldCupYear').onchange=updateStatsYear;$t('#runTournament').onclick=runTournament;$t('#runManySimulations').onclick=runManySimulations;loadTournamentTeams()}
initTournament();